#baseURL = "https://mg-immigration.github.io/website/"
baseURL = "https://mg-immigration.github.io/"
languageCode = "en-us"
title = "GoMig - Immigration Services"
theme = "hugo-arcana"
copyright = "© MG Immigration. All rights reserved"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2
    [languages.es]
        languageName = "Spanish"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/monica-guayara/"

    [params.footer]

        [[params.footer.links]]
            header = "Pages"
        [[params.footer.links.links]]
            title = "Home"
            url = "./"
        [[params.footer.links.links]]
            title = "About Us"
            url = "./about_us/"
        [[params.footer.links.links]]
            title = "Services"
            url = "./services/"
        [[params.footer.links.links]]
            title = "Consultation"
            url = "./consultation/"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
